output "gateway_public_ip" {
  value = openstack_networking_floatingip_v2.gateway_fip.address
}

output "db_internal_ip" {
  value = openstack_compute_instance_v2.db_node.access_ip_v4
}

output "app_internal_ips" {
  value = openstack_compute_instance_v2.app_node[*].access_ip_v4
}

output "auth_internal_ip" {
  value = openstack_compute_instance_v2.auth_node.access_ip_v4
}

# --- ENV FILE GENERATION ---

resource "local_file" "openstack_env" {
  filename = "${path.module}/openstack.env"
  content  = <<EOF
# Generated by Terraform for OpenStack

# --- PUBLIC ACCESS ---
PUBLIC_API_GATEWAY_ENDPOINT=http://${openstack_networking_floatingip_v2.gateway_fip.address}/api
PUBLIC_AUTH_ENDPOINT=http://${openstack_networking_floatingip_v2.gateway_fip.address}/auth
PUBLIC_FRONTEND_URL=http://${openstack_networking_floatingip_v2.gateway_fip.address}

# --- INTERNAL CONFIG ---
DB_HOST=${openstack_compute_instance_v2.db_node.access_ip_v4}
DB_PORT=5432
DB_USER=dbadmin
DB_PASS=${var.db_password}
DB_NAME=myappdb

AUTH_HOST=${openstack_compute_instance_v2.auth_node.access_ip_v4}
AUTH_PORT=8080

# --- STORAGE ---
# Assuming standard Swift port and tenant
SWIFT_AUTH_URL=http://controller:5000/v3
SWIFT_CONTAINER_NAME=${openstack_object_storage_container_v1.media_container.name}
EOF
}
