locals {
  bastion_fip = openstack_networking_floatingip_v2.bastion.address
  lb_fip      = openstack_networking_floatingip_v2.lb.address

  bastion_private_ip = openstack_networking_port_v2.bastion.all_fixed_ips[0]
  backend_private_ip = openstack_networking_port_v2.backend.all_fixed_ips[0]
  db_private_ip      = openstack_networking_port_v2.db.all_fixed_ips[0]
  frontend_private_ips = join(",", [
    for p in openstack_networking_port_v2.frontend : p.all_fixed_ips[0]
  ])
}

resource "local_file" "env" {
  filename        = "${path.module}/.env"
  file_permission = "0600"

  content = <<EOF
# Generated by Terraform. Do not commit.

OS_CLOUD=${var.os_cloud}

BASTION_FLOATING_IP=${local.bastion_fip}
LB_FLOATING_IP=${local.lb_fip}

BASTION_PRIVATE_IP=${local.bastion_private_ip}
FRONTEND_PRIVATE_IPS=${local.frontend_private_ips}
BACKEND_PRIVATE_IP=${local.backend_private_ip}
DB_PRIVATE_IP=${local.db_private_ip}

DB_NAME=${var.db_name}
DB_USER=${var.db_user}
DB_PASSWORD=${random_password.db_password.result}
DB_HOST=${local.db_private_ip}
DB_PORT=5432

SWIFT_CONTAINER=${openstack_objectstorage_container_v1.assets.name}

APP_FRONTEND_READER_USER=${openstack_identity_user_v3.app_frontend_reader.name}
APP_FRONTEND_READER_PASSWORD=${random_password.app_frontend_reader_password.result}

APP_FRONTEND_UPLOADER_USER=${openstack_identity_user_v3.app_frontend_uploader.name}
APP_FRONTEND_UPLOADER_PASSWORD=${random_password.app_frontend_uploader_password.result}
EOF
}
